# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\check memleak\mem_leak_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(382, 377)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(4, -1, 376, 376))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.prv_mem_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_1.setObjectName("prv_mem_1")
        self.gridLayout.addWidget(self.prv_mem_1, 1, 1, 1, 1)
        self.prv_mem_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_12.setObjectName("prv_mem_12")
        self.gridLayout.addWidget(self.prv_mem_12, 2, 1, 1, 1)
        self.prv_mem_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_24.setObjectName("prv_mem_24")
        self.gridLayout.addWidget(self.prv_mem_24, 3, 1, 1, 1)
        self.leak_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_1.setObjectName("leak_1")
        self.gridLayout.addWidget(self.leak_1, 1, 3, 1, 1)
        self.leak_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_12.setObjectName("leak_12")
        self.gridLayout.addWidget(self.leak_12, 2, 3, 1, 1)
        self.leak_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_24.setObjectName("leak_24")
        self.gridLayout.addWidget(self.leak_24, 3, 3, 1, 1)
        self.leak_1_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_1_v.setObjectName("leak_1_v")
        self.gridLayout.addWidget(self.leak_1_v, 1, 4, 1, 1)
        self.prv_mem_1_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_1_v.setObjectName("prv_mem_1_v")
        self.gridLayout.addWidget(self.prv_mem_1_v, 1, 2, 1, 1)
        self.prv_mem_12_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_12_v.setObjectName("prv_mem_12_v")
        self.gridLayout.addWidget(self.prv_mem_12_v, 2, 2, 1, 1)
        self.leak_12_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_12_v.setObjectName("leak_12_v")
        self.gridLayout.addWidget(self.leak_12_v, 2, 4, 1, 1)
        self.prv_mem_24_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.prv_mem_24_v.setObjectName("prv_mem_24_v")
        self.gridLayout.addWidget(self.prv_mem_24_v, 3, 2, 1, 1)
        self.leak_24_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.leak_24_v.setObjectName("leak_24_v")
        self.gridLayout.addWidget(self.leak_24_v, 3, 4, 1, 1)
        self.cur_mem = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cur_mem.setObjectName("cur_mem")
        self.gridLayout.addWidget(self.cur_mem, 0, 1, 1, 1)
        self.cur_mem_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cur_mem_v.setObjectName("cur_mem_v")
        self.gridLayout.addWidget(self.cur_mem_v, 0, 2, 1, 1)
        self.total_mem_leak = QtWidgets.QLabel(self.gridLayoutWidget)
        self.total_mem_leak.setObjectName("total_mem_leak")
        self.gridLayout.addWidget(self.total_mem_leak, 0, 3, 1, 1)
        self.total_mem_leak_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.total_mem_leak_v.setObjectName("total_mem_leak_v")
        self.gridLayout.addWidget(self.total_mem_leak_v, 0, 4, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Mem Leak Monitor"))
        self.prv_mem_1.setText(_translate("mainWindow", "1小时前内存:"))
        self.prv_mem_12.setText(_translate("mainWindow", "12小时前内存:"))
        self.prv_mem_24.setText(_translate("mainWindow", "24小时内存:"))
        self.leak_1.setText(_translate("mainWindow", "1小时内存减少量:"))
        self.leak_12.setText(_translate("mainWindow", "12小时内存减少量:"))
        self.leak_24.setText(_translate("mainWindow", "24小时减少量:"))
        self.leak_1_v.setText(_translate("mainWindow", "-"))
        self.prv_mem_1_v.setText(_translate("mainWindow", "-"))
        self.prv_mem_12_v.setText(_translate("mainWindow", "-"))
        self.leak_12_v.setText(_translate("mainWindow", "-"))
        self.prv_mem_24_v.setText(_translate("mainWindow", "-"))
        self.leak_24_v.setText(_translate("mainWindow", "-"))
        self.cur_mem.setText(_translate("mainWindow", "当前内存:"))
        self.cur_mem_v.setText(_translate("mainWindow", "-"))
        self.total_mem_leak.setText(_translate("mainWindow", "总减少量:"))
        self.total_mem_leak_v.setText(_translate("mainWindow", "-"))
